<?php namespace App\Http\Controllers\Api; use App\Enums\UserStatus; use App\Http\Requests\Auth\LoginRequest; use App\Http\Resources\UserResource; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Facades\Password; class AuthController extends ApiController {
 public function login(LoginRequest $request){$user=\App\Models\User::where('email',$request->string('email'))->first(); if(!$user||!Hash::check($request->string('password'),$user->password)) return response()->json(['success'=>false,'message'=>'Email hoặc mật khẩu không đúng.'],422); if($user->status===UserStatus::Blocked->value)return response()->json(['success'=>false,'message'=>'Tài khoản đã bị khóa.'],403); Auth::login($user,$request->boolean('remember'));$request->session()->regenerate();$user->update(['last_login_at'=>now()]);return $this->success(new UserResource($user),'Đăng nhập thành công');}
 public function logout(Request $request){Auth::guard('web')->logout();$request->session()->invalidate();$request->session()->regenerateToken();return $this->success(null,'Đã đăng xuất');}
 public function me(Request $request){return $this->success(new UserResource($request->user()));}
 public function forgot(Request $request){$request->validate(['email'=>['required','email']]);$status=Password::sendResetLink($request->only('email'));return $status===Password::RESET_LINK_SENT?$this->success(null,__($status)):response()->json(['success'=>false,'message'=>__($status)],422);}
 public function reset(Request $request){$request->validate(['token'=>'required','email'=>'required|email','password'=>'required|confirmed|min:8']);$status=Password::reset($request->only('email','password','password_confirmation','token'),fn($user,$password)=>$user->forceFill(['password'=>$password])->save());return $status===Password::PASSWORD_RESET?$this->success(null,'Đã đặt lại mật khẩu'):response()->json(['success'=>false,'message'=>__($status)],422);}
 public function change(Request $request){$request->validate(['current_password'=>'required','password'=>'required|confirmed|min:8']);if(!Hash::check($request->current_password,$request->user()->password))return response()->json(['success'=>false,'message'=>'Mật khẩu hiện tại không đúng.'],422);$request->user()->update(['password'=>$request->password,'must_change_password'=>false]);return $this->success(null,'Đã đổi mật khẩu');}
 public function sessions(Request $request){return $this->success(\Illuminate\Support\Facades\DB::table('sessions')->where('user_id',$request->user()->id)->orderByDesc('last_activity')->get(['id','ip_address','user_agent','last_activity']));}
 public function destroySession(Request $request,string $session){\Illuminate\Support\Facades\DB::table('sessions')->where('user_id',$request->user()->id)->where('id',$session)->delete();return $this->success(null,'Đã xóa phiên');}
 public function destroyOtherSessions(Request $request){\Illuminate\Support\Facades\DB::table('sessions')->where('user_id',$request->user()->id)->where('id','<>',$request->session()->getId())->delete();return $this->success(null,'Đã xóa các phiên khác');}
}
