<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import AAlert from "ant-design-vue/es/alert";import AButton from "ant-design-vue/es/button";import ACard from "ant-design-vue/es/card";import AEmpty from "ant-design-vue/es/empty";import AInput from "ant-design-vue/es/input";import APagination from "ant-design-vue/es/pagination";import ASelect from "ant-design-vue/es/select";import ATable from "ant-design-vue/es/table";import ATag from "ant-design-vue/es/tag";import ATooltip from "ant-design-vue/es/tooltip";import type { ColumnsType } from "ant-design-vue/es/table/interface";
import { Archive, BookOpen, Pencil, Plus, QrCode, RefreshCw, RotateCcw, Search, UsersRound, UserRound } from "lucide-vue-next";import { toast } from "vue-sonner";
import { archiveChild, createChild, getChild, getChildOptions, listChildren, restoreChild, updateChild, type AdminChild, type AdminListMeta, type ChildCreateInput, type ChildInput, type ChildOptions, type ChildUpdateInput } from "../api/admin";
import AdminActionConfirmModal from "../components/AdminActionConfirmModal.vue";import AdminChildFormModal, { type ChildFormErrors } from "../components/AdminChildFormModal.vue";import AdminChildQrModal from "../components/AdminChildQrModal.vue";import { useAuthStore } from "../stores/authStore";

const auth=useAuthStore();const rows=ref<AdminChild[]>([]);const options=ref<ChildOptions|null>(null);const meta=ref<AdminListMeta>({current_page:1,last_page:1,per_page:15,total:0});const search=ref("");const parishId=ref<number>();const status=ref<"studying"|"paused"|"graduated"|"archived">();const loading=ref(true);const errorMessage=ref("");const formOpen=ref(false);const editing=ref<AdminChild|null>(null);const qrChild=ref<AdminChild|null>(null);const saving=ref(false);const formErrors=ref<ChildFormErrors>({});const discardOpen=ref(false);const action=ref<{type:"archive"|"restore";target:AdminChild}|null>(null);const actionSaving=ref(false);const actionError=ref("");const confirmedUntil=ref(0);
const canCreate=computed(()=>auth.hasPermission("create-children"));const canEdit=computed(()=>auth.hasPermission("update-children"));const canLink=computed(()=>auth.hasPermission("link-parent-child"));const canEnroll=computed(()=>auth.hasPermission("enroll-children"));const canArchive=computed(()=>auth.hasPermission("delete-children"));const canViewQr=computed(()=>auth.hasPermission("view-child-qr"));const canRotateQr=computed(()=>auth.hasPermission("rotate-child-qr"));const needsPassword=computed(()=>action.value?.type==="archive"&&Date.now()>=confirmedUntil.value);
const columns:ColumnsType<AdminChild>=[{title:"Thiếu nhi",key:"person",width:290},{title:"Giáo xứ & lớp",key:"class",responsive:["md"]},{title:"Gia đình",key:"parents",width:180,responsive:["lg"]},{title:"Trạng thái",key:"status",width:145},{title:"",key:"action",width:canViewQr.value?144:104,fixed:"right",align:"center"}];
const apiMessage=(error:unknown,fallback:string)=>(error as {response?:{data?:{message?:string}}}).response?.data?.message??fallback;
function validationErrors(error:unknown):ChildFormErrors{const source=(error as {response?:{data?:{errors?:Record<string,string[]>}}}).response?.data?.errors??{};return Object.fromEntries(Object.entries(source).map(([key,value])=>[key,value[0]])) as ChildFormErrors;}
function tag(row:AdminChild){if(row.is_archived)return{color:"default",label:"Đã lưu trữ"};if(row.status==="paused")return{color:"warning",label:"Tạm nghỉ"};if(row.status==="graduated")return{color:"blue",label:"Đã hoàn thành"};return{color:"success",label:"Đang học"};}
async function load(page=1){loading.value=true;errorMessage.value="";try{const response=await listChildren({search:search.value.trim()||undefined,parish_id:parishId.value,status:status.value,page});rows.value=response.data.data;meta.value=response.data.meta as unknown as AdminListMeta;}catch(error){errorMessage.value=apiMessage(error,"Không thể tải danh sách thiếu nhi.");}finally{loading.value=false;}}
async function loadOptions(){try{options.value=(await getChildOptions()).data.data;}catch{toast.error("Không thể tải dữ liệu lựa chọn.");}}
function openCreate(){editing.value=null;formErrors.value={};formOpen.value=true;}
async function openEdit(row:AdminChild){if(!canEdit.value||row.is_archived)return;loading.value=true;try{editing.value=(await getChild(row.id)).data.data;formErrors.value={};formOpen.value=true;}catch(error){toast.error(apiMessage(error,"Không thể tải hồ sơ thiếu nhi."));}finally{loading.value=false;}}
function closeForm(){formOpen.value=false;editing.value=null;formErrors.value={};discardOpen.value=false;}function requestClose(dirty:boolean){if(saving.value)return;dirty?discardOpen.value=true:closeForm();}
async function save(payload:ChildInput){if(saving.value)return;saving.value=true;formErrors.value={};try{const current=editing.value;current?await updateChild(current.id,payload as ChildUpdateInput):await createChild(payload as ChildCreateInput);toast.success(current?"Đã cập nhật thiếu nhi.":"Đã tạo hồ sơ thiếu nhi.");closeForm();await Promise.all([load(current?meta.value.current_page:1),loadOptions()]);}catch(error){formErrors.value=validationErrors(error);toast.error(apiMessage(error,"Không thể lưu hồ sơ thiếu nhi."));}finally{saving.value=false;}}
function requestAction(type:"archive"|"restore",target:AdminChild){action.value={type,target};actionError.value="";}
async function confirmAction(password:string){if(!action.value||actionSaving.value)return;actionSaving.value=true;actionError.value="";try{if(needsPassword.value){await auth.confirmPassword(password);confirmedUntil.value=Date.now()+15*60*1000;}const pending=action.value;pending.type==="archive"?await archiveChild(pending.target.id):await restoreChild(pending.target.id);toast.success(pending.type==="archive"?"Đã lưu trữ thiếu nhi.":"Đã khôi phục thiếu nhi.");action.value=null;await Promise.all([load(meta.value.current_page),loadOptions()]);}catch(error){actionError.value=apiMessage(error,"Không thể thực hiện thao tác.");toast.error(actionError.value);}finally{actionSaving.value=false;}}
function rowInteractions(row:AdminChild){return{class:canEdit.value&&!row.is_archived?"family-row":"",tabindex:canEdit.value&&!row.is_archived?0:-1,"aria-label":`Chỉnh sửa thiếu nhi ${row.full_name}`,onClick:()=>void openEdit(row),onKeydown:(event:KeyboardEvent)=>{if((event.key==="Enter"||event.key===" ")&&canEdit.value&&!row.is_archived){event.preventDefault();void openEdit(row);}}};}
onMounted(async()=>{await Promise.all([load(),loadOptions()]);});
</script>

<template>
    <section class="family-page"><AAlert v-if="errorMessage" type="error" show-icon closable :message="errorMessage" class="mb-4" @close="errorMessage=''" />
        <ACard :bordered="false" class="admin-card admin-table-card"><header class="family-toolbar"><div><h2>Danh sách thiếu nhi</h2><p>{{ meta.total.toLocaleString('vi-VN') }} hồ sơ phù hợp</p></div><AButton v-if="canCreate" type="primary" size="large" @click="openCreate"><template #icon><Plus class="size-4" /></template>Tạo thiếu nhi</AButton></header>
            <div class="family-filters"><AInput v-model:value="search" allow-clear size="large" placeholder="Tìm theo tên, mã hoặc tên thánh" @press-enter="load(1)"><template #prefix><Search class="size-4 text-slate-400" /></template></AInput><ASelect v-model:value="parishId" allow-clear show-search option-filter-prop="label" size="large" placeholder="Tất cả giáo xứ" :options="options?.parishes.map(item=>({value:item.id,label:item.name}))??[]" @change="load(1)" /><ASelect v-model:value="status" allow-clear size="large" placeholder="Mọi trạng thái" :options="[{value:'studying',label:'Đang học'},{value:'paused',label:'Tạm nghỉ'},{value:'graduated',label:'Đã hoàn thành'},{value:'archived',label:'Đã lưu trữ'}]" @change="load(1)" /><AButton type="primary" size="large" :loading="loading" @click="load(1)"><template #icon><Search class="size-4" /></template>Lọc</AButton><ATooltip title="Tải lại"><AButton size="large" aria-label="Tải lại danh sách" :loading="loading" @click="load(meta.current_page)"><template #icon><RefreshCw class="size-4" /></template></AButton></ATooltip></div>
            <ATable :columns="columns" :data-source="rows" :custom-row="rowInteractions" :loading="loading" :pagination="false" :scroll="{x:880}" row-key="id"><template #emptyText><AEmpty description="Không có thiếu nhi phù hợp." /></template><template #bodyCell="{column,record}">
                <template v-if="column.key==='person'"><div class="flex min-w-0 items-center gap-3"><span class="family-avatar"><UserRound class="size-5" /></span><div class="min-w-0"><b class="block truncate text-[13px] text-blue-950">{{ record.full_name }}</b><span class="mt-0.5 block truncate text-xs text-slate-500">{{ record.code }}<template v-if="record.saint_name"> · {{ record.saint_name }}</template></span></div></div></template>
                <template v-else-if="column.key==='class'"><div class="text-xs text-slate-700"><b class="block truncate font-medium">{{ record.parish.name }}</b><span class="mt-1 flex items-center gap-1.5 text-slate-500"><BookOpen class="size-3.5" />{{ record.current_class?.name||'Chưa xếp lớp' }}</span></div></template>
                <template v-else-if="column.key==='parents'"><span class="flex items-center gap-2 text-xs text-slate-600"><UsersRound class="size-4 text-slate-400" />{{ record.parents_count }} phụ huynh</span></template>
                <template v-else-if="column.key==='status'"><ATag :color="tag(record as AdminChild).color">{{ tag(record as AdminChild).label }}</ATag></template>
                <template v-else-if="column.key==='action'"><div class="flex justify-center gap-1"><ATooltip v-if="canViewQr&&!record.is_archived" title="Xem mã QR"><AButton type="text" class="icon-action-button" aria-label="Xem mã QR thiếu nhi" @click.stop="qrChild=record as AdminChild"><template #icon><QrCode class="size-4" /></template></AButton></ATooltip><ATooltip v-if="canEdit&&!record.is_archived" title="Chỉnh sửa"><AButton type="text" class="icon-action-button" aria-label="Chỉnh sửa thiếu nhi" @click.stop="openEdit(record as AdminChild)"><template #icon><Pencil class="size-4" /></template></AButton></ATooltip><ATooltip v-if="canArchive" :title="record.is_archived?'Khôi phục':'Lưu trữ'"><AButton type="text" class="icon-action-button" :class="record.is_archived?'is-success':'is-danger'" :aria-label="record.is_archived?'Khôi phục thiếu nhi':'Lưu trữ thiếu nhi'" @click.stop="requestAction(record.is_archived?'restore':'archive',record as AdminChild)"><template #icon><RotateCcw v-if="record.is_archived" class="size-4" /><Archive v-else class="size-4" /></template></AButton></ATooltip></div></template>
            </template></ATable><div v-if="meta.total>meta.per_page" class="flex justify-end border-t border-slate-100 px-4 py-3"><APagination :current="meta.current_page" :page-size="meta.per_page" :total="meta.total" :show-size-changer="false" responsive @change="load" /></div></ACard>
    </section>
    <AdminChildFormModal :open="formOpen" :child="editing" :options="options" :saving="saving" :errors="formErrors" :can-link="canLink" :can-enroll="canEnroll" @close="requestClose" @submit="save" />
    <AdminChildQrModal :open="Boolean(qrChild)" :child="qrChild" :can-rotate="canRotateQr" @close="qrChild=null" />
    <AdminActionConfirmModal :open="Boolean(action)" :title="action?.type==='archive'?'Lưu trữ thiếu nhi này?':'Khôi phục thiếu nhi này?'" :description="action?.type==='archive'?'Hồ sơ sẽ ẩn khỏi danh sách đang sử dụng. Lịch sử lớp học và liên kết phụ huynh vẫn được bảo toàn.':'Hồ sơ và các liên kết trước đây sẽ được khôi phục.'" :confirm-text="action?.type==='archive'?'Lưu trữ':'Khôi phục'" :target-name="action?.target.full_name" :target-email="action?.target.code" :danger="action?.type==='archive'" :require-password="needsPassword" :loading="actionSaving" :error-message="actionError" @close="action=null" @confirm="confirmAction" />
    <AdminActionConfirmModal :open="discardOpen" title="Bỏ thay đổi chưa lưu?" description="Thông tin vừa nhập sẽ không được lưu lại." confirm-text="Bỏ thay đổi" danger @close="discardOpen=false" @confirm="closeForm" />
</template>

<style scoped>
.family-toolbar{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.25rem 1.25rem .9rem}.family-toolbar h2{margin:0;color:#0b214d;font-size:1rem;font-weight:750}.family-toolbar p{margin:.25rem 0 0;color:#64748b;font-size:.75rem}.family-filters{display:grid;grid-template-columns:minmax(15rem,1fr) minmax(10rem,.5fr) minmax(9rem,.42fr) auto auto;gap:.625rem;padding:0 1.25rem 1rem}.family-avatar{display:grid;width:2.5rem;height:2.5rem;flex:none;place-items:center;border-radius:.75rem;background:#edf4ff;color:#185fce}.family-page :deep(.family-row){cursor:pointer}.family-page :deep(.family-row:hover>td){background:#f8fbff!important}@media(max-width:1023px){.family-filters{grid-template-columns:minmax(0,1fr) minmax(10rem,.6fr) auto}.family-filters>:nth-child(3){grid-column:1/2}}@media(max-width:639px){.family-toolbar{align-items:flex-start;padding:1rem}.family-filters{grid-template-columns:minmax(0,1fr) auto;padding:0 1rem 1rem}.family-filters>:nth-child(2),.family-filters>:nth-child(3),.family-filters>:nth-child(4){grid-column:1/3}}
</style>
